### PR TITLE
Fix bug: person on display is no longer on display after deletion

### LINKED ISSUE #146: Bug Fix: When person is deleted, they are still on display
image

## Bug: 
- I have already deleted Bernice but she is still on the right display pane. I believe the intended behaviour is for Bernice to be removed from the right side as well when she is deleted
- From this interaction seems as though your right pane is not closely tied to the right, let's try to address this in the next iteration!! 😄

### PR DESCRIPTION
**Pull request by potaotototo**
Fixes #146 

# What is this pull request for?
The person deleted remains on the display panel even after the deletion. 

# What does this pull request do? 
Removes the person on display if that person is deleted.

### CODE REVIEW

File: src/main/java/tuteez/logic/commands/DeleteCommand.java [hunk 1]
```diff
@@ -61,6 +61,15 @@ public CommandResult execute(Model model) throws CommandException {
             personToDelete = getPersonToDeleteByName(model, targetName);
         }
 
+        if (model.getLastViewedPerson().get().isPresent()) {
+            if (personToDelete.equals(model.getLastViewedPerson().get().get())) {
+                model.removeLastViewedPerson();
+                String logMessageForPerson =
+                        String.format("Student on display is deleted, Student: %s", personToDelete);
+                logger.info(logMessageForPerson);
```
Comment (luileng) [inline src/main/java/tuteez/logic/commands/DeleteCommand.java:69]: I like your use of logger here
