### PR TITLE
Correct delete error message for incorrect format

### LINKED ISSUE #327: Correct delete error message for incorrect format
`delete 0 li/` throws the error "Names should only contain alphanumeric characters and spaces, and the following special characters: /, -, ', ., ,, (, ), &. It should start with an alphabet and should not be blank."

This error message does not match the input. Instead, we should change it to the more general error message for delete

### PR DESCRIPTION
**Pull request by luileng**
Fixes #327

## What is this PR for?
`delete 0 li/` throws the error for invalid names. This error message does not match the input. Instead, we should change it to the more general error message for delete

## What does this PR do?
`delete NUMBER ANYTHING` -> throws general delete message usage
eg:
- `delete 0 li/`
- `delete 1 john doe`
- `delete 1 2`

## Note
For `delete john doe li/`, the application will search for a student named `john doe li/` and will not throw an error

### CODE REVIEW

File: src/main/java/tuteez/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -21,9 +21,12 @@ public class DeleteCommandParser implements Parser<DeleteCommand> {
      */
     public DeleteCommand parse(String args) throws ParseException {
         validateNonEmptyArgs(args, DeleteCommand.MESSAGE_USAGE);
-        if (args.trim().matches("-?\\d+")) {
+        String trimmedArgs = args.trim();
```
Comment (weijianwong) [inline src/main/java/tuteez/logic/parser/DeleteCommandParser.java:24]: LGTM
