### PR TITLE
Fix remark json bug

### LINKED ISSUE #90: Fix bug involving remarks from `addressbook.json`
When launching the app, previously inputted remarks are not being loaded from the `addressbook.json` file. As a result, users are unable to retain and view their saved remarks across app sessions.

### PR DESCRIPTION
**Pull request by luileng**
Fixes #90 

## What is this PR for?
When launching the app, previously inputted remarks are not being loaded from the `addressbook.json` file. As a result, users are unable to retain and view their saved remarks across app sessions.

## What does this PR do?
Allows remarks to be loaded from `addressbook.json` file to persons.

### CODE REVIEW

File: src/main/java/tuteez/storage/JsonAdaptedRemarkList.java [hunk 1]
```diff
@@ -26,23 +26,26 @@ public JsonAdaptedRemarkList(@JsonProperty("remarks") List<String> remarks) {
...
      *
      * @throws IllegalValueException if there were any data constraints violated in the adapted remark list.
      */
     public RemarkList toModelType() throws IllegalValueException {
         List<Remark> modelRemarks = new ArrayList<>();
-        for (String remarkStr : remarks) {
-            modelRemarks.add(new Remark(remarkStr));
+        for (String remark : remarks) {
+            if (remark == null || remark.trim().isEmpty()) {
+                throw new IllegalValueException("Remark text cannot be empty");
```
Comment (potaotototo) [inline src/main/java/tuteez/storage/JsonAdaptedRemarkList.java:46]: Do you want to add this into the Messages class?

**Review by potaotototo — COMMENTED** [review]
LGTM! I like the cleanliness of your code.

Just a minor suggestion on whether you want to include the string "Remark cannot be empty" in the Messages class to improve consistency?

File: src/main/java/tuteez/storage/JsonAdaptedPerson.java [hunk 2]
```diff
@@ -83,55 +84,65 @@ public JsonAdaptedPerson(Person source) {
      * @throws IllegalValueException if there were any data constraints violated in the adapted person.
      */
     public Person toModelType() throws IllegalValueException {
-        final List<Tag> personTags = new ArrayList<>();
```
Comment (weijianwong) [inline src/main/java/tuteez/storage/JsonAdaptedPerson.java:86]: Good work with pulling out the logic so that this function becomes much more concise!
