### PR TITLE
Fix display bug

### LINKED ISSUE #121: Fix bug in dynamically displaying person's details
# Problem
Right now, if a person is on display and that person's details are edited, it is not dynamically updated on the display panel but only on the left panel (PersonListPanel).

# Action required
Check through current implementation and make necessary edits to reflect dynamic change of the person's details.

### PR DESCRIPTION
**Pull request by potaotototo**
Fixes #121 

Display card now dynamically displays the student's details after an edit command is executed.

### CODE REVIEW

File: src/main/java/tuteez/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -113,6 +113,16 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         model.setPerson(personToEdit, editedPerson);
+
```
Comment (weijianwong) [inline src/main/java/tuteez/logic/commands/EditCommand.java:116]: LGTM.
